#%RAML 1.0 DataType
type: object
properties:
  customerId:
    type: string
    required: true
    example: ABC-001
  company:
    type: string
    required: true
    example: EECOL
  customerName:
    type: string
    required: true
    example: Ravi
  phone:
    type: string
    required: true
    example: +91-9876543210
  street:
    type: string
    required: true
    example: 12-3-45, MG Road
  city:
    type: string
    required: true
    example: Hyderabad
  state:
    type: string
    required: true
    example: Telangana
  postalCode:
    type: number
    required: true
    example: 500081
  country:
    type: string
    required: true
    example: India
